### ISSUE TITLE
UI Error "Cannot construct unknown type MetadataV7"

### ISSUE THREAD

**Issue by bl0ckchainmaster** [gnunicorn/substrate-offchain-cb#6]
Hi
I found this example very interesting in regards to Offchain workers. So I got the binary from the gitlab release and running it on my linux machine. (my build is failing)
```
./offchain-cb --dev
```
when I try to connect to the client using Polkadot JS App, Getting the following error:
```
FATAL: Unable to initialize the API: createType(Metadata):: Cannot construct unknown type MetadataV7
```
I also check my browser console :
```
API/INIT: Error: createType(Metadata):: Cannot construct unknown type MetadataV7
```
Any idea what I am missing here ?

Thanks
Rez

**Comment by gnunicorn** [comment]
hello @bl0ckchainmaster ,

this repo is terribly out of date and not supported anymore. The idea still sort-of holds true, but it won't work on latest/released substrate because too much has changed. 

To signify that it is deprecated, I have archived this repository now.
